language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
# https://www.reddit.com/r/rust/comments/2p6zxy/heres_how_to_easily_deploy_doc_to_github_pages/
#after_success: |
#    cargo doc \
#    && echo '<meta http-equiv=refresh content=0;url=weltraumschaf/index.html>' > target/doc/index.html && \
#    sudo pip install ghp-import && \
#    ghp-import -n target/doc && \
#    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages