[package]
name = "hello"
version = "1.0.0"
authors = ["Sven Strittmatter <ich@weltraumschaf.de>"]

[dependencies]
clap = "2.29.2"
log = "0.4.1"
simple_logger = "0.3.1"

[dev-dependencies]
hamcrest = "0.1.5"
